name: Deploy FastAPI to EC2 via OpenVPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. OpenVPN 클라이언트 설치
      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      # 3. OpenVPN 연결 (GitHub Secrets에서 OVPN 파일 가져오기)
      - name: Connect to OpenVPN
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" > client.ovpn
          sudo openvpn --config client.ovpn --daemon
          sleep 10  # VPN 연결 대기

      # 4. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t jm-story-be-dev .

      # 5. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 6. Docker Hub에 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker tag jm-story-be-dev ${{ secrets.DOCKER_HUB_USERNAME }}/jm-story-be-dev:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/jm-story-be-dev:latest

      # 7. OpenVPN을 통해 EC2에 SSH 접속하여 배포
      - name: Deploy to EC2 via VPN
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PRIVATE_IP }}  # VPN을 통해 접속 가능
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop jm-story-be-dev || true
            docker rm jm-story-be-dev || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/jm-story-be-dev:latest
            docker run -d --name jm-story-be-dev -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/jm-story-be-dev:latest
